version: '3'
services:
  app:
    build: .
    volumes:
      - user_data:/User

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./htpasswd/.htpasswd:/etc/nginx/.htpasswd
      - ./certificate.pem:/etc/nginx/certificate.pem
      - ./privatekey.pem:/etc/nginx/privatekey.pem
    depends_on:
      - app

volumes:
  user_data:
