  GNU nano 7.2                                     ../docker-compose.yaml                                               version: '3'
services:
  app:
    build: .
    volumes:
      - user_data:/User
    restart: unless-stopped

  nginx:
    image: private-registry.nginx.com/nginx-plus/base:r32-debian
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd/.htpasswd:/etc/nginx/.htpasswd
      - ./ssl/nginx-repo.crt:/etc/ssl/nginx/nginx-repo.crt
      - ./ssl/nginx-repo.key:/etc/ssl/nginx/nginx-repo.key
    depends_on:
      - app
    restart: unless-stopped

volumes:
  user_data:
