version: '3'
services:
  app:
    build: .
    # Ports are not needed if your using Nignx
    #ports:
    #  - "8501:8501"
    #  - "8502:8502"
    #  - "8503:8503"
    volumes:
      - user_data:/User

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./htpasswd/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - app

volumes:
  user_data:
